on:
  push:
    branches:
      - main
    paths:
      - "*.go"
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: docker
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
      - run: go test
