on:
  push:
    branches:
      - main
    paths:
      - "*.go"
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: docker
    container: "node:24-bookworm"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - run: go test
