on:
  push:
    branches:
      - main
    paths:
      - "*.go"
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: docker
    container: "golang:1.25"
    steps:
      - run: apt install git
      # always runs on code from main
      - run: git clone -b ${{ env.FORGEJO_REF_NAME }} https://remotebranch.eu/ChaoticByte/journal.git
      - run: go test -v
        working-directory: ./journal
